# Generated by Django 3.0.1 on 2022-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220617_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile.jpeg', upload_to='profile_pics'),
        ),
    ]
