# Generated by Django 4.0.5 on 2022-06-24 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_to_report', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_month', models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default=1, max_length=2)),
                ('start_year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default=2022, max_length=4)),
                ('end_month', models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default=1, max_length=2)),
                ('end_year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default=2022, max_length=4)),
                ('location', models.CharField(default='', max_length=20)),
                ('budget', models.IntegerField(default=0, max_length=3)),
                ('what_time_do_you_go_to_sleep', models.IntegerField(blank=True, choices=[(1, '21:00'), (2, '22:00'), (3, '23:00'), (4, '24:00+')], null=True)),
                ('how_often_do_you_cook_per_week', models.IntegerField(blank=True, choices=[(1, '0'), (2, '1-2'), (3, '3-4'), (4, '5+')], null=True)),
                ('how_often_do_you_meet_friends_per_week', models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Once per week'), (3, '2-4 times per week'), (4, 'A lot')], null=True)),
                ('how_often_do_you_have_visitors', models.IntegerField(blank=True, choices=[(1, 'Never'), (2, 'Around once a month'), (3, 'Once a week'), (4, 'More than once a week')], null=True)),
                ('when_do_you_usually_return_to_the_flat', models.IntegerField(blank=True, choices=[(1, 'Afternoon'), (2, 'Evening'), (3, 'Late at night'), (4, 'Morning')], null=True)),
                ('how_often_do_you_drink_alcohol', models.IntegerField(blank=True, choices=[(1, "I don't drink"), (2, '1-2 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True)),
                ('when_do_you_shower', models.IntegerField(blank=True, choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Evening'), (4, 'Right before bed')], null=True)),
                ('how_often_do_you_shop_for_groceries', models.IntegerField(blank=True, choices=[(1, 'Once per week'), (2, '2-3 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True)),
                ('how_often_do_you_do_chores', models.IntegerField(blank=True, choices=[(1, 'Once per week'), (2, '2-3 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
