# Generated by Django 4.0.5 on 2022-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_cook_per_week',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1-2'), (3, '3-4'), (4, '5+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_do_chores',
            field=models.IntegerField(blank=True, choices=[(1, 'Once per week'), (2, '2-3 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_drink_alcohol',
            field=models.IntegerField(blank=True, choices=[(1, "I don't drink"), (2, '1-2 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_meet_friends_per_week',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Once per week'), (3, '2-4 times per week'), (4, 'A lot')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_shop_for_groceries',
            field=models.IntegerField(blank=True, choices=[(1, 'Once per week'), (2, '2-3 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_think_you_will_bring_other_people_into_the_flat',
            field=models.IntegerField(blank=True, choices=[(1, 'Never'), (2, 'Around once a month'), (3, 'Once a week'), (4, 'More than once a week')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='what_time_do_you_go_to_sleep',
            field=models.IntegerField(blank=True, choices=[(1, '21:00'), (2, '22:00'), (3, '23:00'), (4, '24:00+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='when_do_you_shower',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Evening'), (4, 'Right before bed')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='when_do_you_usually_return_to_the_flat',
            field=models.IntegerField(blank=True, choices=[(1, 'Afternoon'), (2, 'Evening'), (3, 'Late at night'), (4, 'Morning')], null=True),
        ),
    ]
