# Generated by Django 4.0.5 on 2022-06-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_to_report', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='end_month',
            field=models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='end_year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default=2022, max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_cook_per_week',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1-2'), (3, '3-4'), (4, '5+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_meet_friends_per_week',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Once per week'), (3, '2-4 times per week'), (4, 'A lot')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='start_month',
            field=models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='start_year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default=2022, max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='what_time_do_you_go_to_sleep',
            field=models.IntegerField(blank=True, choices=[(1, '21:00'), (2, '22:00'), (3, '23:00'), (4, '24:00+')], null=True),
        ),
    ]
