# Generated by Django 4.0.5 on 2022-06-29 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_cook_per_week',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1-2'), (3, '3-4'), (4, '5+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_have_guests',
            field=models.IntegerField(blank=True, choices=[(1, 'Never'), (2, 'Around once a month'), (3, 'Once a week'), (4, 'More than once a week')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_meet_friends_per_week',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Once per week'), (3, '2-4 times per week'), (4, 'A lot')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='how_often_do_you_shop_for_groceries',
            field=models.IntegerField(blank=True, choices=[(1, 'Once per week'), (2, '2-3 times per week'), (3, '4-5 times per week'), (4, 'Basically every day')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='what_time_do_you_go_to_sleep',
            field=models.IntegerField(blank=True, choices=[(1, '21:00'), (2, '22:00'), (3, '23:00'), (4, '24:00+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='when_do_you_usually_return_to_the_flat',
            field=models.IntegerField(blank=True, choices=[(1, 'Afternoon'), (2, 'Evening'), (3, 'Late at night'), (4, 'Morning')], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_first_person', to=settings.AUTH_USER_MODEL)),
                ('second_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_second_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_person', 'second_person')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_thread', to='core.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
