# Generated by Django 3.0.1 on 2022-06-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_user', models.CharField(max_length=100)),
                ('report_content', models.TextField()),
            ],
        ),
    ]
