# Generated by Django 4.0.5 on 2022-06-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_content',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_user',
            new_name='username_to_report',
        ),
    ]
