# Generated by Django 4.0.5 on 2022-06-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_how_often_do_you_cook_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='how_often_do_you_drink_alcohol',
        ),
        migrations.RemoveField(
            model_name='post',
            name='how_often_do_you_shop_for_groceries',
        ),
        migrations.RemoveField(
            model_name='post',
            name='when_do_you_shower',
        ),
    ]
