# Generated by Django 4.0.5 on 2022-06-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep', models.IntegerField()),
                ('cook', models.IntegerField()),
                ('loner', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_content',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_user',
            new_name='username_to_report',
        ),
        migrations.AddField(
            model_name='post',
            name='quizDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quiz'),
        ),
    ]
