# Generated by Django 4.0.5 on 2022-06-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_how_often_do_you_drink_alcohol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='how_often_do_you_do_chores',
            new_name='how_often_do_you_shop_for_groceries',
        ),
    ]
