# Generated by Django 4.0.5 on 2022-06-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_how_often_do_you_do_chores_post_how_often_do_you_shop_for_groceries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='how_often_do_you_think_you_will_bring_other_people_into_the_flat',
            new_name='how_often_do_you_have_guests',
        ),
    ]
