# Generated by Django 4.0.5 on 2022-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_budget_post_end_month_post_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quiz',
        ),
        migrations.AddField(
            model_name='post',
            name='cook',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1-2'), (3, '3-4'), (4, '5+')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='loner',
            field=models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Once per week'), (3, '2-4 times per week'), (4, 'A lot')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sleep',
            field=models.IntegerField(blank=True, choices=[(1, '21:00'), (2, '22:00'), (3, '23:00'), (4, '24:00+')], null=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
