# Generated by Django 4.0.5 on 2022-06-24 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_budget_post_search_location_post_studies_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
