# Generated by Django 4.0.5 on 2022-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_end_date_post_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='budget',
            field=models.CharField(blank=True, choices=[('0-500', '£0-500'), ('500-750', '£500-750'), ('750-1000', '£750-1000'), ('1000-1250', '£1000-1250'), ('1250-1500', '£1250-1500'), ('1500-1750', '£1500-1750'), ('1750-2000', '£1750-2000'), ('2000-3000', '£2000-3000'), ('3000+', '£3000+')], max_length=30, null=True),
        ),
    ]
