# Generated by Django 4.0.5 on 2022-06-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_quiz_post_cook_post_loner_post_sleep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cook',
            new_name='how_often_do_you_cook_per_week',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='loner',
            new_name='how_often_do_you_meet_friends_per_week',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sleep',
            new_name='what_time_do_you_go_to_sleep',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quizDone',
        ),
    ]
