# Generated by Django 3.0.1 on 2022-06-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_quesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
